version: '3'
 services:
   crawler:
     image: XXX.dkr.ecr.us-east-1.amazonaws.com/cron:${TAG}
     env_file:
       - ../.env
     logging:
       driver: awslogs
       options: 
         awslogs-region: us-east-1
         awslogs-group: cron
         awslogs-stream-prefix: ${TAG}