AWSTemplateFormatVersion: '2010-09-09'
 Description: >
   Create S3 bucket.
 Parameters:
   BucketName:
     Type: String
   LogGroupName:
     Type: String
 Resources:
  CronBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: !Ref BucketName
   EcsTaskExecutionRole:
     Type: AWS::IAM::Role
     Properties:
       AssumeRolePolicyDocument:
         Version: "2012-10-17"
         Statement:
           -
             Effect: "Allow"
             Principal:
               Service:
                 - "ecs-tasks.amazonaws.com"
             Action:
               - "sts:AssumeRole"
       ManagedPolicyArns:
         - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
       Path: /
   LogGroup:
     Type: AWS::Logs::LogGroup
     Properties:
       LogGroupName: !Ref LogGroupName
       RetentionInDays: 10
